version: "3"

services:

  server:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: evertonv/nodeserver
    container_name: nodeserver
    networks:
      - nodenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: evertonv/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge